# Numeric features used during model training

NUMERIC_FEATURES = [
    "AGE",
    "ANNUAL_INCOME",
    "CREDIT_SCORE",

    "SUM_INSURED",
    "ANNUAL_PREMIUM",
    "RISK_SCORE",
    "DISCOUNT_PCT",
    "COMMISSION_PCT",
    "POLICY_TERM_DAYS",
    "PREMIUM_TO_SUM_INSURED_PCT",

    "HEALTH_SCORE",
    "BMI",
    "UNDERWRITING_SCORE",
    "PREMIUM_LOADING_PCT",

    "OLD_PREMIUM",
    "NEW_PREMIUM",
    "PREMIUM_INCREASE_PCT",
    "PREMIUM_CHANGE_AMOUNT",
    "NEW_PREMIUM_TO_INCOME_PCT",
    "LOYALTY_YEARS",

    "TOTAL_DUE_TXNS_PRIOR",
    "PAID_TXNS_PRIOR",
    "UNPAID_TXNS_AT_RENEWAL",
    "TOTAL_PREMIUM_DUE_PRIOR",
    "TOTAL_PREMIUM_PAID_PRIOR",
    "AVG_PAYMENT_DELAY_PRIOR",
    "MAX_PAYMENT_DELAY_PRIOR",
    "PAYMENT_SUCCESS_RATE_PRIOR",

    "TOTAL_CLAIMS_PRIOR",
    "TOTAL_CLAIM_AMOUNT_PRIOR",
    "AVG_CLAIM_AMOUNT_PRIOR",
    "MAX_CLAIM_AMOUNT_PRIOR",
    "DAYS_SINCE_LAST_CLAIM",

    "HAS_PAYMENT_HISTORY_PRIOR",
    "HAS_CLAIM_HISTORY_PRIOR",
    "HAS_UNPAID_PAYMENT_AT_RENEWAL",
    "HAS_UNDERWRITING_RECORD",
    "PREMIUM_INCREASED_FLAG",
    "HIGH_PREMIUM_INCREASE_FLAG"
]


# Categorical features

CATEGORICAL_FEATURES = [
    "GENDER",
    "MARITAL_STATUS",
    "OCCUPATION",
    "STATE",
    "CUSTOMER_RISK_SEGMENT",

    "POLICY_TYPE",
    "SALES_CHANNEL",
    "PAYMENT_MODE",
    "RISK_BAND",

    "LIFESTYLE",
    "MEDICAL_HISTORY_FLAG",
    "SMOKER_FLAG",
    "OCCUPATION_RISK",
    "UW_DECISION",

    "CONTACT_CHANNEL"
]


# All model input features

ALL_FEATURES = (
    NUMERIC_FEATURES
    +
    CATEGORICAL_FEATURES
)

# print(ALL_FEATURES)