USE InsuranceAnalyticsDB;
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name='analytics')
    EXEC('CREATE SCHEMA analytics');
GO

IF OBJECT_ID('analytics.ai_chat_sessions','U') IS NULL
BEGIN
CREATE TABLE analytics.ai_chat_sessions(
    SESSION_ID VARCHAR(100) PRIMARY KEY,
    CREATED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UPDATED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    LAST_INTENT VARCHAR(50) NULL
);
END;
GO

IF OBJECT_ID('analytics.ai_chat_messages','U') IS NULL
BEGIN
CREATE TABLE analytics.ai_chat_messages(
    MESSAGE_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    SESSION_ID VARCHAR(100) NOT NULL,
    ROLE VARCHAR(30) NOT NULL,
    MESSAGE_TEXT NVARCHAR(MAX) NOT NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_AI_CHAT_MESSAGE_SESSION FOREIGN KEY(SESSION_ID)
        REFERENCES analytics.ai_chat_sessions(SESSION_ID),
    CONSTRAINT CK_AI_CHAT_MESSAGE_ROLE CHECK(ROLE IN ('user','assistant','system'))
);
END;
GO

IF OBJECT_ID('analytics.ai_tool_audit','U') IS NULL
BEGIN
CREATE TABLE analytics.ai_tool_audit(
    AUDIT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    SESSION_ID VARCHAR(100) NOT NULL,
    TOOL_NAME VARCHAR(100) NOT NULL,
    TOOL_ARGS_JSON NVARCHAR(MAX) NULL,
    TOOL_RESULT_JSON NVARCHAR(MAX) NULL,
    STATUS VARCHAR(30) NOT NULL,
    ERROR_MESSAGE NVARCHAR(2000) NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_AI_TOOL_AUDIT_SESSION FOREIGN KEY(SESSION_ID)
        REFERENCES analytics.ai_chat_sessions(SESSION_ID)
);
END;
GO
